INSERT ALL INTO Genre (GenreName)
	VALUES('Shounen')
INTO Genre (GenreName)
	VALUES('Shounen Ai')
INTO Genre (GenreName)
	VALUES('Seinen')
INTO Genre (GenreName)
	VALUES('Shoujo')
INTO Genre (GenreName)
	VALUES('Shoujo Ai')
INTO Genre (GenreName)
	VALUES('Josei')
INTO Genre (GenreName)
	VALUES('Comedy')
INTO Genre (GenreName)
	VALUES('Romance')
INTO Genre (GenreName)
	VALUES('School')
INTO Genre (GenreName)
	VALUES('Action')
INTO Genre (GenreName)
	VALUES('Adventure')
INTO Genre (GenreName)
	VALUES('Cars')
INTO Genre (GenreName)
	VALUES('Dementia')
INTO Genre (GenreName)
	VALUES('Demons')
INTO Genre (GenreName)
	VALUES('Drama')
INTO Genre (GenreName)
	VALUES('Ecchi')
INTO Genre (GenreName)
	VALUES('Fantasy')
INTO Genre (GenreName)
	VALUES('Game')
INTO Genre (GenreName)
	VALUES('Harem')
INTO Genre (GenreName)
	VALUES('Historical')
INTO Genre (GenreName)
	VALUES('Horror')
INTO Genre (GenreName)
	VALUES('Kids')
INTO Genre (GenreName)
	VALUES('Magic')
INTO Genre (GenreName)
	VALUES('Martial Arts')
INTO Genre (GenreName)
	VALUES('Mecha')
INTO Genre (GenreName)
	VALUES('Military')
INTO Genre (GenreName)
	VALUES('Music')
INTO Genre (GenreName)
	VALUES('Mystery')
INTO Genre (GenreName)
	VALUES('Parody')
INTO Genre (GenreName)
	VALUES('Police')
INTO Genre (GenreName)
	VALUES('Psychological')
INTO Genre (GenreName)
	VALUES('Samurai')
INTO Genre (GenreName)
	VALUES('Sci-Fi')
INTO Genre (GenreName)
	VALUES('Slice of Life')
INTO Genre (GenreName)
	VALUES('Space')
INTO Genre (GenreName)
	VALUES('Sports')
INTO Genre (GenreName)
	VALUES('Super Power')
INTO Genre (GenreName)
	VALUES('Supernatural')
INTO Genre (GenreName)
	VALUES('Vampire')
INTO Genre (GenreName)
	VALUES('Thriller')
INTO Genre (GenreName)
	VALUES('Hentai')
INTO Genre (GenreName)
	VALUES('Yaoi')
INTO Genre (GenreName)
	VALUES('Yuri')
	SELECT * FROM DUAL;

INSERT ALL INTO TypeAnime (TypeAnimeName)
	VALUES('TV Series')
INTO TypeAnime (TypeAnimeName)
	VALUES('Movie')
INTO TypeAnime (TypeAnimeName)
	VALUES('OVA')
INTO TypeAnime (TypeAnimeName)
	VALUES('ONA')
INTO TypeAnime (TypeAnimeName)
	VALUES('Special')
INTO TypeAnime (TypeAnimeName)
	VALUES('Music')
	SELECT * FROM DUAL;

INSERT ALL INTO Season (SeasonName)
	VALUES('Winter')
INTO Season (SeasonName)
	VALUES('Spring')
INTO Season (SeasonName)
	VALUES('Summer')
INTO Season (SeasonName)
	VALUES('Fall') 
	SELECT * FROM DUAL;

INSERT ALL INTO Status (StatusName)
	VALUES('Announced')
INTO Status (StatusName)
	VALUES('Ongoing')
INTO Status (StatusName)
	VALUES('Finished')
INTO Status (StatusName)
	VALUES('Unknown')
	SELECT * FROM DUAL;

INSERT ALL INTO Country (CountryName)
	VALUES('Japan')
INTO Country (CountryName)
	VALUES('China')
INTO Country (CountryName)
	VALUES('Korea')
INTO Country (CountryName)
	VALUES('America')
	SELECT * FROM DUAL;

INSERT ALL INTO Studio (StudioName)
	VALUES('J.C.Staff')
INTO Studio (StudioName)
	VALUES('Pierrot')
INTO Studio (StudioName)
	VALUES('A-1 Pictures')
INTO Studio (StudioName)
	VALUES('CloverWorks')
INTO Studio (StudioName)
	VALUES('P.A. Works')
INTO Studio (StudioName)
	VALUES('Bones')
	SELECT * FROM DUAL;

INSERT ALL INTO Censorship (CensorshipName)
	VALUES('G')
INTO Censorship (CensorshipName)
	VALUES('PG')
INTO Censorship (CensorshipName)
	VALUES('PG-13')
INTO Censorship (CensorshipName)
	VALUES('R-17')
INTO Censorship (CensorshipName)
	VALUES('R+')
INTO Censorship (CensorshipName)
	VALUES('Rx')
	SELECT * FROM DUAL;

INSERT ALL INTO DurationAnime (DurationName)
	VALUES('Less than 10 min')
INTO DurationAnime (DurationName)
	VALUES('~15 min')
INTO DurationAnime (DurationName)
	VALUES('~24 min')
INTO DurationAnime (DurationName)
	VALUES('30+ min')
INTO DurationAnime (DurationName)
	VALUES('~60 min')
INTO DurationAnime (DurationName)
	VALUES('~90 min')
INTO DurationAnime (DurationName)
	VALUES('120+ min')
	SELECT * FROM DUAL;

INSERT ALL INTO Author (Firstname, Surname, Nickname, AuthorLink)
	VALUES('Reki', 'Kawahara', NULL,'https://twitter.com/kunori')
INTO Author (Firstname, Surname, Nickname, AuthorLink)
	VALUES('Masashi', 'Kishimoto', NULL, NULL)
INTO Author (Firstname, Surname, Nickname, AuthorLink)
	VALUES('Yuuto', 'Tsukuda', NULL, 'https://twitter.com/tsukudayuto')
INTO Author (Firstname, Surname, Nickname, AuthorLink)
	VALUES('Hajime', 'Kamoshida', NULL, NULL)
INTO Author (Firstname, Surname, Nickname, AuthorLink)
	VALUES('Risou', 'Maeda', NULL, 'http://maedarisou.blog136.fc2.com')
INTO Author (Firstname, Surname, Nickname, AuthorLink)
	VALUES('Ichirou', 'Sakaki', NULL, 'http://www.ugougo.net')
	SELECT * FROM DUAL;

INSERT ALL INTO TypeOriginal (TypeOriginalName)
	VALUES('Manga')
INTO TypeOriginal (TypeOriginalName)
	VALUES('Manhwa')
INTO TypeOriginal (TypeOriginalName)
	VALUES('Manhua')
INTO TypeOriginal (TypeOriginalName)
	VALUES('One Shot')
INTO TypeOriginal (TypeOriginalName)
	VALUES('Doujin')
INTO TypeOriginal (TypeOriginalName)
	VALUES('Light Novel')
	SELECT * FROM DUAL;

INSERT INTO AuthorReview (Firstname, Surname, Nickname, AuthorReviewLink)
	VALUES('Bogdan', 'King', 'Manuscript','Link :)');

INSERT ALL INTO Editor (Firstname, Surname, Nickname, EditorLink)
	VALUES('Kristina', 'Lis', 'FireFoX_DefT','Link :)')
INTO Editor (Firstname, Surname, Nickname, EditorLink)
	VALUES('Tanya', 'Akinchic', 'taya_aki','Link :)')
	SELECT * FROM DUAL;

INSERT ALL INTO Review (ReviewNumber, id_AuthorReview, id_Editor, Link, DataPublication)
	VALUES(1, 1, NULL, 'Link :)', TO_DATE('28/03/2019','DD.MM.YYYY'))
INTO Review (ReviewNumber, id_AuthorReview, id_Editor, Link, DataPublication)
	VALUES(2, 1, NULL, 'Link :)', TO_DATE('28/03/2019','DD.MM.YYYY'))
	SELECT * FROM DUAL;

INSERT ALL INTO Original (EngilshName, id_Genre, id_Genre1, id_Genre2, id_Genre3, id_Genre4, id_Genre5, id_Author, id_TypeOriginal, id_Status, ReleaseOriginal)
	VALUES('Nagi no Asu kara', 15, 17, 8, 9, NULL, NULL, 5, 1, 3, 2013)
INTO Original (EngilshName, id_Genre, id_Genre1, id_Genre2, id_Genre3, id_Genre4, id_Genre5, id_Author, id_TypeOriginal, id_Status, ReleaseOriginal)
	VALUES('Hitsugi no Chaika', 7, 17, 8, 11, 10, NULL, 6, 6, 3, 2010)
	SELECT * FROM DUAL;

INSERT ALL INTO Anime ( OriginalName, RussianName, id_Genre, id_Genre1, id_Genre2, id_Genre3, id_Genre4, id_Genre5, ReleaseAnime, id_TypeAnime, id_Season, id_Season1, id_Season2, id_Season3, id_Status, id_Country, id_Studio, id_Censorship, id_DurationAnime, Rating, id_Original, NumberOfSeasons, NumberOfEpisodes, id_Review)
	VALUES('Nagi no Asu kara', NULL, 15, 17, 8, 9, NULL, NULL, 2013, 1, 4, 1, NULL, NULL, 3, 1, 5, 3, 3, '8,14', 1, 1, 26, 1)
INTO Anime (OriginalName, RussianName, id_Genre, id_Genre1, id_Genre2, id_Genre3, id_Genre4, id_Genre5, ReleaseAnime, id_TypeAnime, id_Season, id_Season1, id_Season2, id_Season3, id_Status, id_Country, id_Studio, id_Censorship, id_DurationAnime, Rating, id_Original, NumberOfSeasons, NumberOfEpisodes, id_Review)
	VALUES('Hitsugi no Chaika', NULL, 7, 17, 8, 11, 10, NULL, 2014, 1, 2, NULL, NULL, NULL, 3, 1, 6, 4, 3, '7,32', 2, 1, 12, 2)
	SELECT * FROM DUAL;