CREATE SEQUENCE Seq_Genre
INCREMENT BY 1
START WITH 1 NOMAXVALUE; 


CREATE SEQUENCE Seq_TypeAnime
INCREMENT BY 1
START WITH 1 NOMAXVALUE;


CREATE SEQUENCE Seq_Season
INCREMENT BY 1
START WITH 1 NOMAXVALUE;


CREATE SEQUENCE Seq_Status
INCREMENT BY 1
START WITH 1 NOMAXVALUE;


CREATE SEQUENCE Seq_Country
INCREMENT BY 1
START WITH 1 NOMAXVALUE;


CREATE SEQUENCE Seq_Studio
INCREMENT BY 1
START WITH 1 NOMAXVALUE;


CREATE SEQUENCE Seq_Censorship
INCREMENT BY 1
START WITH 1 NOMAXVALUE;


CREATE SEQUENCE Seq_DurationAnime
INCREMENT BY 1
START WITH 1 NOMAXVALUE;


CREATE SEQUENCE Seq_Author
INCREMENT BY 1
START WITH 1 NOMAXVALUE;


CREATE SEQUENCE Seq_TypeOriginal
INCREMENT BY 1
START WITH 1 NOMAXVALUE;


CREATE SEQUENCE Seq_AuthorReview
INCREMENT BY 1
START WITH 1 NOMAXVALUE;


CREATE SEQUENCE Seq_Editor
INCREMENT BY 1
START WITH 1 NOMAXVALUE;


CREATE SEQUENCE Seq_Review
INCREMENT BY 1
START WITH 1 NOMAXVALUE;


CREATE SEQUENCE Seq_Original
INCREMENT BY 1
START WITH 1 NOMAXVALUE;


CREATE SEQUENCE Seq_Anime
INCREMENT BY 1
START WITH 1 NOMAXVALUE;